pluginManagement {
    apply from: new File(settingsDir, 'gradle/codeartifact.gradle')

    repositories {
        maven {
            name = "codeartifact"
            url = codeArtifact.publicUrl
            credentials {
                username = "aws"
                password = codeArtifact.getAuthToken()
            }
        }
        gradlePluginPortal()
    }
}

include ':sample', ':library', ':library-no-op'
